# ECOWAS Border Trade Intelligence and Analytics

# Power BI Data Preparation

## Impact Assessment of Simulated Regional Trade Diversion Following the AES Countries' Withdrawal from ECOWAS

### Case Study: Tsamiya–Kamba Transit Corridor

---

## Objective

This notebook prepares analytical datasets for visualization in Microsoft Power BI.

The goal is to transform the transaction-level data into clean summary tables that can be imported directly into Power BI for interactive dashboards and executive reporting.

In [1]:
# ============================================================
# Chapter 1 - Import Libraries
# ============================================================

import pandas as pd

print("Libraries imported successfully.")

Libraries imported successfully.

In [2]:
# ============================================================
# Chapter 2 - Load Dataset
# ============================================================

df = pd.read_csv("trade_diversion_transactions.csv")

print(df.shape)

df.head()

(100000, 20)

,Transaction_ID,Transaction_Date,Period,Origin_Country,Entry_Country,Destination_Country,Border_Post,Commodity,Vehicle_Type,Cargo_Weight_kg,Trade_Value_USD,Customs_Duty_USD,Revenue_Collected_USD,Queue_Length,Processing_Time_Minutes,Inspection_Result,Smuggling_Risk,Security_Incident,Scanner_Status,Border_Efficiency_Score
0,TRX0000001,2025-08-02,After Diversion,Togo,Cape Verde,Niger,Praia Port,Vehicles,Heavy Truck,23091.78,70960.57,9435.26,9791.44,17,25.9,Passed,Medium,No,Unavailable,98.0
1,TRX0000002,2022-08-17,Before Diversion,Nigeria,Togo,Niger,Kodjoviakope,Livestock,Heavy Truck,16533.94,63340.83,11608.49,11799.07,22,48.0,Passed,Low,No,Unavailable,82.3
2,TRX0000003,2022-02-21,Before Diversion,Benin,Benin,Niger,Hillacondji,Vehicles,Passenger Bus,943.86,13943.07,2766.44,2833.49,25,46.5,Passed,Medium,No,Unavailable,76.8
3,TRX0000004,2023-07-18,Before Diversion,Benin,Sierra Leone,Nigeria,Gbalamuya,Petroleum,Heavy Truck,18142.28,83276.36,13714.69,13775.83,6,20.5,Passed,Medium,No,Available,95.3
4,TRX0000005,2023-05-17,Before Diversion,Benin,Mali,Nigeria,Gogui,Vehicles,Heavy Truck,19017.79,62190.16,10388.67,10554.40,26,54.9,Passed,Low,No,Available,79.7

## Create Date Dimension

Power BI performs best when using a dedicated Date table for time-based analysis.

In [3]:
# ============================================================
# Chapter 3 - Date Table
# ============================================================

df["Transaction_Date"] = pd.to_datetime(df["Transaction_Date"])
df["Year"] = df["Transaction_Date"].dt.year

df["Month"] = df["Transaction_Date"].dt.month

df["Month_Name"] = df["Transaction_Date"].dt.month_name()

df["Quarter"] = df["Transaction_Date"].dt.quarter
date_table = pd.DataFrame({

    "Date": sorted(df["Transaction_Date"].unique())

})

date_table["Year"] = date_table["Date"].dt.year
date_table["Month"] = date_table["Date"].dt.month
date_table["Month_Name"] = date_table["Date"].dt.month_name()
date_table["Quarter"] = date_table["Date"].dt.quarter

date_table.head()

        Date  Year  Month Month_Name  Quarter
0 2022-01-01  2022      1    January        1
1 2022-01-02  2022      1    January        1
2 2022-01-03  2022      1    January        1
3 2022-01-04  2022      1    January        1
4 2022-01-05  2022      1    January        1

## Border Performance Summary

This table summarizes operational performance by border post.

In [4]:
# ============================================================
# Chapter 4 - Border Summary
# ============================================================

border_summary = (

    df.groupby("Border_Post")

    .agg({

        "Transaction_ID":"count",

        "Trade_Value_USD":"sum",

        "Revenue_Collected_USD":"sum",

        "Queue_Length":"mean",

        "Processing_Time_Minutes":"mean",

        "Border_Efficiency_Score":"mean"

    })

    .reset_index()

)

border_summary

,Border_Post,Transaction_ID,Trade_Value_USD,Revenue_Collected_USD,Queue_Length,Processing_Time_Minutes,Border_Efficiency_Score
0,Aflao,2612,1.405737e+08,18425257.09,22.572358,44.308844,83.194410
1,Amdallai,3031,1.608466e+08,20662748.43,22.320356,43.864137,83.338568
2,Bo Waterside,3540,1.897958e+08,24217075.11,22.727119,44.710113,83.085706
3,Cinkanse,5504,2.903418e+08,37720302.83,22.549964,44.344967,83.208703
4,Elubo,2706,1.433368e+08,18308650.53,22.696970,44.271877,83.246489
5,Gaya,5338,2.867480e+08,37357217.26,22.495879,44.142806,83.297377
6,Gbalamuya,3468,1.851335e+08,23821839.56,22.742503,44.641782,83.163783
7,Gogui,5466,2.900902e+08,37039457.22,22.610318,44.474515,83.138273
8,Hillacondji,6611,3.540514e+08,45471352.72,22.611556,44.435380,83.208546
9,Illela,2636,1.413604e+08,18387635.49,22.120258,43.749127,83.563012
10,Jibia,2288,1.213439e+08,15509998.32,22.461538,44.346941,83.151311
11,Kamba,4895,2.628111e+08,33655170.00,69.267824,105.138631,54.654362
12,Kidira,5139,2.742509e+08,35005284.17,22.347149,44.291594,83.227145
13,Kodjoviakope,6100,3.264973e+08,42272743.73,22.604426,44.413033,83.182443
14,Konni,5436,2.876743e+08,37067911.70,22.474982,44.163723,83.310063
15,Kouremale,4662,2.480262e+08,31856631.62,22.320678,44.252252,83.315744
16,Malanville,6633,3.553884e+08,45736299.53,45.140510,73.590351,69.416011
17,Noe,2898,1.550424e+08,20093601.73,22.376812,43.966184,83.372809
18,Paga,2713,1.447276e+08,18514492.85,22.491338,44.169075,83.330409
19,Pogo,2988,1.596707e+08,20295565.32,22.656292,44.576874,83.173728
20,Praia Port,2451,1.305909e+08,16670672.17,22.459404,44.291718,83.231987
21,Sao Domingos,2970,1.566466e+08,20292146.36,22.463636,44.113939,83.402660
22,Seme,3520,1.835372e+08,23695650.77,45.165341,73.537813,69.440739
23,Tsamiya,6395,3.412729e+08,43904800.29,71.713995,108.034965,53.286396

## Commodity Summary

Summarize trade activity and revenue by commodity.

In [5]:
# ============================================================
# Chapter 5 - Commodity Summary
# ============================================================

commodity_summary = (

    df.groupby("Commodity")

    .agg({

        "Trade_Value_USD":"sum",

        "Revenue_Collected_USD":"sum",

        "Transaction_ID":"count"

    })

    .reset_index()

)

commodity_summary

,Commodity,Trade_Value_USD,Revenue_Collected_USD,Transaction_ID
0,Agricultural Produce,4.130169e+08,5.333761e+07,7663
1,Construction Materials,5.823168e+08,7.453293e+07,10902
2,Electronics,5.371690e+08,6.930176e+07,10049
3,Fertilizer,2.661360e+08,3.418171e+07,4973
4,Livestock,4.813193e+08,6.220152e+07,9000
5,Petroleum,7.418711e+08,9.575366e+07,13990
6,Pharmaceuticals,4.743106e+08,6.107939e+07,8900
7,Rice,8.650819e+08,1.109856e+08,16297
8,Textiles,4.841460e+08,6.235231e+07,9087
9,Vehicles,4.843910e+08,6.225603e+07,9139

## Monthly Performance Summary

Prepare monthly performance indicators for trend analysis.

In [6]:
# ============================================================
# Chapter 6 - Monthly Summary
# ============================================================

monthly_summary = (

    df.groupby(["Year","Month_Name"])

    .agg({

        "Trade_Value_USD":"sum",

        "Revenue_Collected_USD":"sum",

        "Transaction_ID":"count"

    })

    .reset_index()

)

monthly_summary

    Year Month_Name  Trade_Value_USD  Revenue_Collected_USD  Transaction_ID
0   2022      April     1.097885e+08            14069010.90            2051
1   2022     August     1.145687e+08            14713512.37            2164
2   2022   December     1.103850e+08            14292907.94            2059
3   2022   February     1.033415e+08            13349102.20            1909
4   2022    January     1.145106e+08            14692661.12            2153
5   2022       July     1.167337e+08            14980227.04            2143
6   2022       June     1.086149e+08            14102169.56            2080
7   2022      March     1.115754e+08            14389160.64            2080
8   2022        May     1.134172e+08            14487972.42            2123
9   2022   November     1.107001e+08            14169309.64            2060
10  2022    October     1.188979e+08            15405272.33            2193
11  2022  September     1.037265e+08            13429075.54            2001
12  2023      April     1.104084e+08            14127018.44            2057
13  2023     August     1.098849e+08            14065092.83            2085
14  2023   December     1.071810e+08            13898231.19            2025
15  2023   February     9.969979e+07            12985731.36            1850
16  2023    January     1.138272e+08            14927579.53            2152
17  2023       July     1.124079e+08            14392055.07            2106
18  2023       June     1.074466e+08            13630714.62            2032
19  2023      March     1.111176e+08            14091255.25            2108
20  2023        May     1.109949e+08            14267706.45            2074
21  2023   November     1.093245e+08            14031955.94            2051
22  2023    October     1.155553e+08            14866056.14            2147
23  2023  September     1.083570e+08            14040509.79            2040
24  2024      April     1.118193e+08            14273756.60            2080
25  2024     August     1.133964e+08            14698791.04            2115
26  2024   December     1.084887e+08            13895369.59            2042
27  2024   February     1.085869e+08            13910164.82            2031
28  2024    January     1.079585e+08            13957964.53            2075
29  2024       July     1.139583e+08            14773658.01            2133
30  2024       June     1.136959e+08            14682844.45            2129
31  2024      March     1.146519e+08            14836632.92            2162
32  2024        May     1.142934e+08            14557175.23            2144
33  2024   November     1.067080e+08            13834282.82            2003
34  2024    October     1.158974e+08            14942372.04            2167
35  2024  September     1.104731e+08            14111716.41            2038
36  2025      April     1.068122e+08            13701401.45            2025
37  2025     August     1.150046e+08            14862035.15            2162
38  2025   December     1.093941e+08            14104285.81            2051
39  2025   February     1.017874e+08            13125154.07            1915
40  2025    January     1.072318e+08            13828828.72            2075
41  2025       July     1.164000e+08            14956430.77            2150
42  2025       June     1.081264e+08            14034911.60            2040
43  2025      March     1.157051e+08            14665892.43            2165
44  2025        May     1.130570e+08            14606962.65            2116
45  2025   November     1.190640e+08            15160149.80            2247
46  2025    October     1.108047e+08            14315922.17            2084
47  2025  September     1.139782e+08            14741513.41            2108

## Country Summary

Aggregate transaction activity by entry country.

In [7]:
# ============================================================
# Chapter 7 - Country Summary
# ============================================================

country_summary = (

    df.groupby("Entry_Country")

    .agg({

        "Trade_Value_USD":"sum",

        "Revenue_Collected_USD":"sum",

        "Transaction_ID":"count"

    })

    .reset_index()

)

country_summary

    Entry_Country  Trade_Value_USD  Revenue_Collected_USD  Transaction_ID
0           Benin     7.094398e+08           9.120765e+07           13244
1    Burkina Faso     2.903418e+08           3.772030e+07            5504
2      Cape Verde     1.305909e+08           1.667067e+07            2451
3   Cote d'Ivoire     3.147131e+08           4.038917e+07            5886
4           Ghana     4.286381e+08           5.524840e+07            8031
5          Guinea     2.480262e+08           3.185663e+07            4662
6   Guinea-Bissau     1.566466e+08           2.029215e+07            2970
7         Liberia     1.897958e+08           2.421708e+07            3540
8            Mali     2.900902e+08           3.703946e+07            5466
9           Niger     5.744223e+08           7.442513e+07           10774
10        Nigeria     1.050326e+09           1.351533e+08           19734
11        Senegal     2.742509e+08           3.500528e+07            5139
12   Sierra Leone     1.851335e+08           2.382184e+07            3468
13     The Gambia     1.608466e+08           2.066275e+07            3031
14           Togo     3.264973e+08           4.227274e+07            6100

## Border Post Dimension

This dimension table contains one record for each border post.

It will be used to create relationships within the Power BI data model.

In [8]:
# ============================================================
# Chapter 8 - Border Dimension
# ============================================================

border_dimension = (

    df[[
        "Border_Post",
        "Entry_Country"
    ]]

    .drop_duplicates()

    .sort_values("Border_Post")

    .reset_index(drop=True)

)

border_dimension.head()

    Border_Post Entry_Country
0         Aflao         Ghana
1      Amdallai    The Gambia
2  Bo Waterside       Liberia
3      Cinkanse  Burkina Faso
4         Elubo         Ghana

## Commodity Dimension

This table contains one record for each commodity.

It simplifies filtering and reporting in Power BI.

In [9]:
# ============================================================
# Chapter 9 - Commodity Dimension
# ============================================================

commodity_dimension = (

    df[["Commodity"]]

    .drop_duplicates()

    .sort_values("Commodity")

    .reset_index(drop=True)

)

commodity_dimension

                Commodity
0    Agricultural Produce
1  Construction Materials
2             Electronics
3              Fertilizer
4               Livestock
5               Petroleum
6         Pharmaceuticals
7                    Rice
8                Textiles
9                Vehicles

## Country Dimension

This table contains the countries participating in the simulated trade transactions.

In [10]:
# ============================================================
# Chapter 10 - Country Dimension
# ============================================================

country_dimension = (

    df[["Entry_Country"]]

    .drop_duplicates()

    .sort_values("Entry_Country")

    .reset_index(drop=True)

)

country_dimension

    Entry_Country
0           Benin
1    Burkina Faso
2      Cape Verde
3   Cote d'Ivoire
4           Ghana
5          Guinea
6   Guinea-Bissau
7         Liberia
8            Mali
9           Niger
10        Nigeria
11        Senegal
12   Sierra Leone
13     The Gambia
14           Togo

## Data Quality Assessment

Verify that the dataset contains no missing values before exporting to Power BI.

In [11]:
# ============================================================
# Chapter 11 - Missing Values
# ============================================================

missing = df.isnull().sum()

missing

Transaction_ID             0
Transaction_Date           0
Period                     0
Origin_Country             0
Entry_Country              0
Destination_Country        0
Border_Post                0
Commodity                  0
Vehicle_Type               0
Cargo_Weight_kg            0
Trade_Value_USD            0
Customs_Duty_USD           0
Revenue_Collected_USD      0
Queue_Length               0
Processing_Time_Minutes    0
Inspection_Result          0
Smuggling_Risk             0
Security_Incident          0
Scanner_Status             0
Border_Efficiency_Score    0
Year                       0
Month                      0
Month_Name                 0
Quarter                    0
dtype: int64

## Dataset Information

Review the structure and data types of the dataset.

In [12]:
# ============================================================
# Chapter 12 - Dataset Information
# ============================================================

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 24 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Transaction_ID           100000 non-null  object
 1   Transaction_Date         100000 non-null  datetime64[ns]
 2   Period                   100000 non-null  object
 3   Origin_Country           100000 non-null  object
 4   Entry_Country            100000 non-null  object
 5   Destination_Country      100000 non-null  object
 6   Border_Post              100000 non-null  object
 7   Commodity                100000 non-null  object
 8   Vehicle_Type             100000 non-null  object
 9   Cargo_Weight_kg          100000 non-null  float64
 10  Trade_Value_USD          100000 non-null  float64
 11  Customs_Duty_USD         100000 non-null  float64
 12  Revenue_Collected_USD    100000 non-null  float64
 13  Queue_Length             100000 non-null  int64
 14  Processing_Time_Minutes  100000 non-null  float64
 15  Inspection_Result        100000 non-null  object
 16  Smuggling_Risk           100000 non-null  object
 17  Security_Incident        100000 non-null  object
 18  Scanner_Status           100000 non-null  object
 19  Border_Efficiency_Score  100000 non-null  float64
 20  Year                     100000 non-null  int32
 21  Month                    100000 non-null  int32
 22  Month_Name               100000 non-null  object
 23  Quarter                  100000 non-null  int32
dtypes: datetime64[ns](1), float64(6), int32(3), int64(1), object(13)
memory usage: 17.2+ MB

## Export Tables

Export all prepared tables for Power BI.

In [13]:
# ============================================================
# Chapter 13 - Export Tables
# ============================================================

df.to_csv(
    "fact_transactions.csv",
    index=False
)

date_table.to_csv(
    "dim_date.csv",
    index=False
)

border_summary.to_csv(
    "border_summary.csv",
    index=False
)

commodity_summary.to_csv(
    "commodity_summary.csv",
    index=False
)

monthly_summary.to_csv(
    "monthly_summary.csv",
    index=False
)

country_summary.to_csv(
    "country_summary.csv",
    index=False
)

border_dimension.to_csv(
    "dim_border.csv",
    index=False
)

commodity_dimension.to_csv(
    "dim_commodity.csv",
    index=False
)

country_dimension.to_csv(
    "dim_country.csv",
    index=False
)

print("All Power BI tables exported successfully.")

All Power BI tables exported successfully.

## Verify Export

Confirm that all Power BI files have been created successfully.

In [14]:
# ============================================================
# Chapter 14 - Verify Export
# ============================================================

import os

files = sorted(os.listdir())

for file in files:
    if file.endswith(".csv"):
        print(file)

border_summary.csv
commodity_summary.csv
country_summary.csv
dim_border.csv
dim_commodity.csv
dim_country.csv
dim_date.csv
fact_transactions.csv
monthly_summary.csv
trade_diversion_transactions.csv

# Power BI Data Model

The exported files support a star-schema design.

## Fact Table

- fact_transactions.csv

## Dimension Tables

- dim_date.csv
- dim_border.csv
- dim_country.csv
- dim_commodity.csv

## Summary Tables

- border_summary.csv
- commodity_summary.csv
- monthly_summary.csv
- country_summary.csv

This structure is suitable for building interactive dashboards using slicers, filters, maps, KPIs, and trend analyses.